### ISSUE TITLE
Add Lyric search API

### ISSUE THREAD

**Issue by KGCan** [KGCan/Lyrical#2]
add API for lyric search

**Comment by KGCan** [comment]
lyrics.ovh

**Comment by megphillips21** [comment]
- Lyrics.ovh will be sent data from the search in spotify API
- Spotify API will narrow done song title search to a song + artist name to run in this API

**Comment by jazzminsharee** [comment]
added fetch request for lyrics.ovh api and pushed it to my feature branch
